function  imageBatchExport(dispPathname, actFilenameList)

%--------------------------------------------------------------------------
% GUI Components
%--------------------------------------------------------------------------

f = figure('Visible','off','Position',[360,500,800,690],...
    'WindowStyle', 'normal',...
    'MenuBar', 'none', ...
    'Color', 'white');

%---------Block 1----------------
hOctOn = uicontrol('Style','checkbox','String', 'OCT',...
    'Value', 0, ...
    'BackgroundColor', 'white',...
    'FontSize', 12,...
    'Position',[10,590,180,40]);

hSloOn = uicontrol('Style','checkbox','String', 'OCT',...
    'Value', 0, ...
    'BackgroundColor', 'white',...
    'FontSize', 12,...
    'Position',[10,590,180,40]);

hDataPop = uicontrol('Style','popupmenu',...
    'String',{'<None>','<ForceColumns>','ILM HE', 'RPE HE', 'ONFL HE',  ...
    'Retina Thickness HE', 'RNFL Thickness HE', ...
    'ILM OCTSEG', 'RPE OCTSEG', 'ONFL OCTSEG', ...
    'Retina Thickness OCTSEG', 'RNFL Thickness OCTSEG'},...
    'Position',[10,100,380,40]);

%------------Save Button---------------
hExport = uicontrol('Style','pushbutton','String','Export Images',...
    'Position',[10,10,780,80],...
    'FontSize', 16,...
    'Callback',{@hExport_Callback});

%--------------------------------------------------------------------------
% GUI Init
%--------------------------------------------------------------------------

set([f, hOctOn, hSloOn, ...
    hSave],'Units','normalized');
set(f,'Name','Vol Info Reader');

movegui(f,'center');
set(f,'Visible','on');

%--------------------------------------------------------------------------
% GUI Component Handlers
%--------------------------------------------------------------------------

    function hExport_Callback(hObject, eventdata)
      
    end


    function figure_CloseRequestFcn(hObject, eventdata, handles)
        uiresume(hObject);
        delete(hObject);
    end

end
