function ok = prerequisiteOK(DataDescriptors, reqTag, segDescriptor, segType)
% CHECKPREREQUISITE Checks is a prerequisite (automated segmentation) for
% another type ('automated', 'manual') of segmentation is fullfilled. The
% descriptors should contain strings according to the definitions in
% octsegConstantVariables. The tag is ONE tag generated by getMetaTag.

global PROCESSEDFILES;

ok = 1;

status = checkFilesIfProcessed(DataDescriptors, reqTag);
if status ~= PROCESSEDFILES.ALL
    notifierText(['Perform ' reqDescriptor ' segmentation for each BScan before ' ...
        segType ' ' segDescriptor ' segmentation!']);
    ok = 0;
end